stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -s settings.xml"

build:
  stage: build
  image: maven:3.5.3-jdk-8-alpine
  script:
    - mvn clean install $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/

build_image:
  stage: build_image
  dependencies:
    - build_and_test
  script:
    - ls target/
    - docker build --tag $SERVICE_NAME:$CI_PIPELINE_ID .
    - docker rmi $SERVICE_NAME:$CI_PIPELINE_ID